### ISSUE TITLE
Feature request: star and label log folders/files

### ISSUE THREAD

**Issue by RobertMouncer** [CSS-Electronics/cancloud#18]
Not sure if you're taking feaute requests, but here is one just incase:

Have the ability to:
 - Add a star next to log files/folders
 - Add labels next to files/folders

It may look something like this (obviously a lot better):
![request](https://user-images.githubusercontent.com/44447819/91185510-d5609f80-e6e5-11ea-85fd-26919b0e40c5.png)

**Comment by MatinF** [comment]
Hi Robert, thanks for the suggestion, it makes sense. We'll discuss it internally. 

One way this could be done would be as follows:
1) CANcloud could be modified to parse a `meta.json` file with a comment field, e.g. as follows:
```
{
"00000557": "Vehicle issue #45 occurred",
"00000578": "Vehicle issue #42 occurred"
}
```
2) Such a `meta.json` file could then be uploaded by end users at the root of a device folder and if present, the information will be displayed next to the relevant sessions. If no `meta.json` file is available, nothing is displayed

I'd have to check if this would be sensible to add, but let me know if the above concept would be suitable in your opinion.

**Comment by RobertMouncer** [comment]
In my use case, I have given engineers within the company read only access to the S3 server, so that files cannot be deleted or modified. I guess if I would want engineers to make notes on log files, full access would be required.

I think what you have suggested is a very good solution, except having to download and reupload the file when required. If an interface were available, that would be an ideal solution, though it wouldn't be the end of the world.

An interface idea:
- Add the three dots to folders
![image](https://user-images.githubusercontent.com/44447819/91213770-fdfa9080-e709-11ea-8d2e-9a8a4e9d9bf8.png)

- Add a pencil option (like below)
![image](https://user-images.githubusercontent.com/44447819/91213831-17034180-e70a-11ea-89b7-b736b4fe0ad0.png)

- Then a simple popup occurs
![image](https://user-images.githubusercontent.com/44447819/91214132-91cc5c80-e70a-11ea-9dd9-89b393f8612f.png)

Btw loving the tool! Thank you CSS.

**Comment by MatinF** [comment]
Hi again,

The interface you propose could be a good v2.0 of the solution I mentioned. 

Note that since CANcloud is only a 'browser', it is necessary to have some form of object stored on your specific S3 server in order to "persist" the changes. So for example if you create such a change as you suggest, the only way to make sure the change also shows up the next time is to create an object stored e.g. in that device folder as proposed.

As such, if you provide access for engineers to enter CANcloud and view the files with read-only model, you would not be able to allow them to create such notes even if we were to add an interface, unless their credentials allow for creating new objects on S3. 

It might be that there's an option of limiting their ability to create files to only be with certain suffixes etc through policies. That way you could allow for creating a `meta.json` file, but e.g. block modifying the config-XX.YY.json files (thus blocking OTA updates from those users).

Happy to hear your thoughts on this,
Martin

**Comment by MatinF** [comment]
Closing this as I believe we will not at this stage add support for it in the CANcloud master build.
